import mwparserfromhell

text = """
Test: {{{1. Singular Indikativ Präsens Aktiv|{{#if: {{{Präsens|{{{Präsens Aktiv|{{{Hauptsatzkonjugation|{{{unpersönlich|}}}}}}}}}}}}| —| {{#switch: {{{3}}} | e= {{#ifeq: {{{4}}} | l | ich {{{1}}}{{{2}}}{{{4}}}e{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}},<br />ich {{{1}}}{{{2}}}{{{3}}}{{{4}}}{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}},<br />ich {{{1}}}{{{2}}}{{{3}}}{{{4}}}e {{{Teil 1|}}} {{{Teil 2|}}} | ich {{{1}}}{{{2}}}{{{3}}}{{{4}}}{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}},<br />ich {{{1}}}{{{2}}}{{{3}}}{{{4}}}e{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}},<br /> ich {{{1}}}{{{2}}}{{{4}}}e {{{Teil 1|}}} {{{Teil 2|}}}}} | m={{#switch: {{{2}}} | b | c | ch | d | f | g | j | k | p | s | t | v | w | x | z | ß=ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}} | #default=ich {{{1}}}{{{2}}}{{{3}}}{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}}, <br />ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}}}} | n={{#switch: {{{2}}} | b | c | ch | d | f | g | j | k | m | p | s | t | v | w | x | z | ß=ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}} | #default=ich {{{1}}}{{{2}}}{{{3}}}{{#if: {{{Teil 1|}}}|&#32;{{{Teil 1}}}{{#if: {{{Teil 2|}}}|&#32;{{{Teil 2}}}|}}|}}, <br />ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}}}} | r= {{#ifeq: {{{4}}} | l | ich {{{1}}}{{{2}}}{{{3}}}{{{4}}}e {{{Teil 1|}}} {{{Teil 2|}}}|ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}}}} | d | t=ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}} | #default= {{#ifeq: {{{4}}} | e | {{#switch: {{{2}}} | t | ch=ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}} | #default=ich {{{1}}}{{{2}}}{{{3}}}e {{{Teil 1|}}} {{{Teil 2|}}}}} }} }} }} }}}
"""

wikicode = mwparserfromhell.parse(text)

templates = wikicode.filter_templates()
print(templates[0].params)
print(wikicode)